#!/usr/bin/env bash
set -e

echo "============================================"
echo " 合伙算钱 → CopilotKit 重构方案"
echo "============================================"
echo ""
echo "一、当前项目结构"
echo "  client/      ← 手写 index.html + app.js (纯静态)"
echo "  server/      ← Express + SQLite + DeepSeek API"
echo "    index.js      ← 路由+认证"
echo "    seed.js       ← 种子数据"
echo "    ai.js         ← AI 调用"
echo "    prompt.js     ← 提示词拼接"
echo "    matcher.js    ← 知识库匹配引擎"
echo ""
echo "二、CopilotKit 集成方案"
echo ""
echo "方案A: 渐进式（推荐）"
echo "  不改后端，只替换前端"
echo "  - 新建 packages/web/ 作为 CopilotKit React 前端"
echo "  - 后端依旧 Express + DeepSeek，适配为 CopilotKit runtime"
echo "  - 保留现有 seed.js + matcher.js 知识库"
echo "  - 保留 .env 配置"
echo "  难度: ★★☆☆☆  风险: 低  工期: 1-2天"
echo ""
echo "方案B: 全栈替换"
echo "  前后端都换 CopilotKit"
echo "  - 后端改用 CopilotKit Agent runtime (LangGraph)"
echo "  - 前端用 CopilotKit React"
echo "  - 知识库用 langmem 或向量库"
echo "  难度: ★★★★☆  风险: 中  工期: 3-5天"
echo ""
echo "三、推荐第一步"
echo "  1. npx copilotkit@latest init （在项目根目录）"
echo "  2. 将现有 Express + SQLite 封装为 CopilotKit Agent"
echo "  3. 前端留空，用 CopilotKit Chat UI 替代手写表单"
echo ""
echo "四、注意事项"
echo "  - Render 免费计划内存 512MB，CopilotKit 额外约 150MB"
echo "  - DeepSeek API 兼容 openai SDK，CopilotKit 原生支持"
echo "  - 知识库 matcher.js 可以保留，不用向量库"
echo ""
echo "等待确认后执行..."
